scandipwa/create-magento-app

- build-packages/magento-scripts/index.js
- build-packages/magento-scripts/lib/commands/start.js
- build-packages/magento-scripts/lib/util/prefix.js
Reverts scandipwa/create-magento-app#23
> Revert "Added Google Analytic for CMA"

- build-packages/magento-scripts/lib/config/versions/magento-2.3.7-p1.js
- build-packages/magento-scripts/lib/config/versions/magento-2.3.7.js
- build-packages/magento-scripts/lib/config/versions/magento-2.4.2-p1.js
- build-packages/magento-scripts/lib/config/versions/magento-2.4.2-p2.js
- build-packages/magento-scripts/lib/config/versions/magento-2.4.2.js
- build-packages/magento-scripts/lib/config/versions/magento-2.4.3-p1.js
- build-packages/magento-scripts/lib/config/versions/magento-2.4.3.js
- build-packages/magento-scripts/lib/tasks/composer/index.js
- build-packages/magento-scripts/lib/util/config-file-validator.js
> FIx Magento does not support Composer 2.2

- build-packages/create-magento-app/index.js
- build-packages/create-magento-app/lib/dependency/arch.js
- build-packages/create-magento-app/lib/dependency/centos.js
- build-packages/create-magento-app/lib/dependency/dependencies-for-platforms.js
- build-packages/create-magento-app/lib/dependency/fedora.js
- build-packages/create-magento-app/lib/dependency/index.js
- build-packages/create-magento-app/lib/dependency/install-dependencies.js
- build-packages/create-magento-app/lib/dependency/mac.js
- build-packages/create-magento-app/lib/dependency/ubuntu.js
- build-packages/create-magento-app/lib/exec-async.js
- build-packages/create-magento-app/lib/os-platform.js
- build-packages/create-magento-app/package.json
> add dependency check to create-magento-app

- build-packages/magento-scripts/lib/tasks/composer/index.js
Fixes #35 
So if Composer fails to install the following will be printed in the terminal:
> add troubleshooting to composer installation step

- build-packages/magento-scripts/lib/tasks/magento/enable-magento-composer-plugins.js
- build-packages/magento-scripts/lib/tasks/start.js
FIxes #46 
Demo:
https://user-images.githubusercontent.com/18352350/148243713-bfda2434-f5d1-408f-a086-67d6c658487e.mp4
> handle allow-plugins config for composer 2.2 and newer

- build-packages/magento-scripts/lib/tasks/mysql/connect-to-mysql.js
> change host parameter value to 127.0.0.1 instead of localhost in mysql connection options

- build-packages/magento-scripts/lib/tasks/magento/setup-magento/adjust-magento-configuration.js
- build-packages/magento-scripts/lib/tasks/magento/setup-magento/configure-elasticsearch.js
- build-packages/magento-scripts/lib/tasks/magento/setup-magento/delete-admin-users.js
- build-packages/magento-scripts/lib/tasks/mysql/dump-theme-config.js
- build-packages/magento-scripts/lib/util/database.js
> check if table exists in database before working with it

- build-packages/magento-scripts/lib/commands/start.js
- build-packages/magento-scripts/lib/tasks/magento/setup-magento/set-base-url.js
- build-packages/magento-scripts/lib/tasks/start.js
> use correct urls for projects running with SSL enabled

- build-packages/magento-scripts/lib/tasks/requirements/dependency/ubuntu.js
> run apt update before installing missing dependencies on ubuntu

- build-packages/magento-scripts/lib/commands/logs.js
Fix #56 
This is how it looks:
> add logs command description

- build-packages/magento-scripts/lib/tasks/start.js
- build-packages/magento-scripts/lib/util/open-browser.js
- build-packages/magento-scripts/lib/util/xdg-open-exists.js
> check for xdg-open in path on WSL system

- build-packages/magento-scripts/lib/commands/start.js
> make startup timings to be reported in ms

- build-packages/magento-scripts/lib/tasks/php/compile-options.js
> change curl-openssl dependency to curl for compiling php on mac

- build-packages/magento-scripts/lib/tasks/composer/index.js
> fix composer version parsing

- build-packages/magento-scripts-php-ioncube-extension/index.js
> handle missing Downloads directory for ioncube

- build-packages/magento-scripts/lib/commands/start.js
- build-packages/magento-scripts/lib/tasks/magento/setup-magento/set-base-url.js
- build-packages/magento-scripts/lib/util/instance-metadata.js
> add support for running cma with ngrok, update start command output

- build-packages/magento-scripts/lib/tasks/requirements/docker/index.js
- build-packages/magento-scripts/lib/tasks/requirements/docker/permissions.js
> add prompt fixing permission issues with docker socket

- build-packages/magento-scripts/lib/tasks/requirements/docker/index.js
- build-packages/magento-scripts/lib/tasks/requirements/docker/install.js
- build-packages/magento-scripts/lib/tasks/requirements/docker/running-status.js
- build-packages/magento-scripts/lib/tasks/requirements/docker/version.js
- build-packages/magento-scripts/lib/util/systemctl.js
Now CMA will check if the Docker service is running and if not will prompt to enable and/or run it
> fix docker is not running

- build-packages/magento-scripts/lib/tasks/database/import-dump-to-database.js
There's a lowercase letter, should be uppercase.
> Fix typo lowercase letter.

- build-packages/magento-scripts/lib/tasks/database/import-remote-db/ssh/index.js
- build-packages/magento-scripts/lib/tasks/database/import-remote-db/ssh/readymage.js
- build-packages/magento-scripts/lib/tasks/database/import-remote-db/ssh/regular-server.js
- build-packages/magento-scripts/lib/util/set-config.js
- build-packages/magento-scripts/package.json
- yarn.lock
- replace node-ssh with node-ssh-no-cpu-features package for testing
> bump magento-scripts dependency versions
